# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71087d06ba3795edd7c856c0c5ec2e8747e2decb9e94901425937f85177265c5a37c2ca42823ac4958a5a228d74365b759b134a761f16b3e8d810fbaac13a86d

test:
  secret_key_base: c733543cbbbe25cc89e3cca931ac092713eb624fa8f3ca82e9d93ca0d9b4ae8e7d595760747d323534aa23cd812bbbbeafe3d535dd489330f5ec66579526e537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
